blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.views import register, UpdateUserView, ProfileDetail, ProfileEditView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register', register, name="register"),
    path('accounts/', include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('settings', UpdateUserView.as_view(), name='settings'),
    path('profile/<slug>', ProfileDetail.as_view(), name='profile'),
    path('profile/<slug>/edit', ProfileEditView.as_view(), name='edit-profile'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    PostDetailView,
                    BlogPostLikes,
                    CommentDeleteView,
                    CategoryView)

app_name = 'core'

urlpatterns = [
    path('', PostListView.as_view(), name="home"),
    # path('article/<slug>', PostDetailView.as_view(), name="detail"),
    path('article/<slug>', PostDetailView.as_view(), name="detail"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('article/<slug>/update', PostUpdateView.as_view(), name="update"),
    path('article/<slug>/delete', PostDeleteView.as_view(), name="delete"),
    path('blogpost-like/<slug>', BlogPostLikes, name='like'),
    path('article/<slug>/delete', PostDeleteView.as_view(), name="delete"),
    path('comment/<int:pk>', CommentDeleteView.as_view(), name="dltz"),
    path('category/<str:catg>', CategoryView, name="category"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from ckeditor.fields import RichTextField

LABEL_CHOICES = (
    ('E', 'economy'),
    ('P', 'politic'),
    ('S', 'sport'),
    ('T', 'tech'),
)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # content = models.TextField()
    content = RichTextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    post_image = models.ImageField(upload_to='post/cover')
    category = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    likes = models.ManyToManyField(User, related_name='blogpost_like')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:detail", kwargs={
            'slug': self.slug
        })

    def delete(self, *args, **kwargs):
        self.post_image.delete()
        super().delete(*args, **kwargs)

    @property
    def comment_numbers(self):
        return Comment.objects.filter(post=self).count()

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)
    comment = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

templates/base.html
<!DOCTYPE html>
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{%block title %} {%endblock%}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>

<body>

 <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="/" >
                    <strong class="blue-text">Blog</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link waves-effect" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                    </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link waves-effect font-weight-bold" href="{%url 'core:create'%}">Publish a Post </a>
                            </li>

                             <li class="nav-item dropdown">
                                <a class="nav-link waves-effect " href="{% url 'profile' user.username %}" >Profile</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link waves-effect " href="{% url 'edit-profile' user.username %}" >Edit Profile</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'settings' %}" >settings</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'logout' %}" >Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'login' %}">Login</a>
                            </li>

                             <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'register' %}" >Signup</a>
                            </li>
                        {% endif %}

                    </ul>

                </div>

            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->




    <!--Main layout-->
    <main class="mt-5 pt-5">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                {% endfor %}
            {% endif %}


        <div class="container" >

            {% block content %}
            {% endblock content %}

        </div>
    </main>
    <!--Main layout-->

<!--Footer-->
    <footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">

        <hr class="my-4">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-youtube mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-google-plus-g mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-dribbble mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-pinterest mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-codepen mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2021
            <a href="" target="_blank"></a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>
</body>


</html>

templates/category.html
{% extends 'base.html' %}

   {% include 'partials/_navbar.html' %}

{% block title %}
  {{catg}}
{% endblock %}

{% block content%}

 <section class="text">
    <hr class="my-5">
    <!-- Grid row -->
  <div class="row">
    {% for post in category_posts %}
    <!-- Grid column -->
    <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-2 mb-4">
        <img class="img-fluid" src="{{post.post_image.url}}"    alt="Sample image" style="height:300px;">
        <a href="{% url 'core:detail' post.slug %}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

      <!-- Category -->
      <a href="#!" class=" red-text">
        <h6 class="font-weight-bold mb-3"><i class="fas fa-map pr-2"></i>{{post.get_category_display}}</h6>
      </a>

      <!-- Post title -->

    <a href="{% url 'core:detail' post.slug %}">
      <h4 href= class="font-weight-bold mb-3"><strong>{{post.title}}</strong></h4>
    </a>

      <!-- Post data -->
      <p>by <a class="font-weight-bold">{{post.author}}</a>, {{post.date_created | date:"F d Y"}}</p>
      <!-- Excerpt -->
      <p class="dark-grey-text">{{post.content|truncatewords:50|safe}}</p>
      <!-- Read more button -->
      <a href="{% url 'core:detail' post.slug %}" class="btn btn-blue btn-rounded btn-md mb-5">Read more</a>

    </div>
</div>
    {%endfor%}

</div>

    <!--Grid row-->

    <!--Pagination-->
    {% if is_paginated%}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous%}
          <li class="page-item  ">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
            <li class="page-item ml-2">
            <a class="page-link" href="?page=1">{{page_obj.previous_page_number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}

            <li class="page-item   ml-2">
            <a class="page-link" href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>

          {% endif %}
        </ul>
      </nav>
      {% endif %}


</section>

{% endblock content %}

{% include 'partials/_footer.html '%}

</body>

</html>

templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Publis a Post
{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST"  enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form.media }}
                {{ form | crispy }}
            </fieldset>
            <div class='form-group'>
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block title %}
  {{post.title}}
{% endblock %}


{% block content %}
<div class="container">

  <!-- Grid row -->
  <div class="row mt-5">

    <!-- Grid column -->
    <div class="col-md-8 mb-4">

      <h1 class="font-weight-bold">{{post.title | upper}}</h1>

      <div class="card my-4">
        <img src="{{post.post_image.url}}" class="img-fluid" alt="">

      </div>
       <p>by <a href="{% url 'profile' post.author.profile.user.username  %}" class="font-weight-bold">{{post.author}}</a>, {{post.date_created | date:"F d Y"}}</p>
       {% if request.user == post.author %}
          <a href="{% url 'core:update' post.slug %}" class="badge bg-info">Edit Your Post</a>
          <a href="{% url 'core:delete' post.slug %}" class="badge bg-danger">Delete</a>
        {% endif %}
        <p align="justify">{{ post.content | safe }}

      <h4 class="text-center font-weight-bold mb-3">Share this article</h4>
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item"><a><i class="fab fa-facebook-f fa-lg px-2 text-primary"></i></a></li>
        <li class="list-inline-item"><a><i class="fab fa-twitter fa-lg px-2 text-info"></i></a></li>
        <li class="list-inline-item"><a><i class="far fa-envelope fa-lg px-2 text-default"></i></a></li>
      </ul>

      {% if user.is_authenticated %}
  <form action="{% url 'core:like' object.id %}" method="POST">
    {% csrf_token %}

      {% if post_is_liked %}
      <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-info btn-sm">Unlike</button>
      {% else %}
      <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-info btn-sm">Like</button>
      {% endif %}
    </form>
  {% else %}
    <a class="btn btn-info btn-sm" href="{% url 'login' %}?next={{request.path}}">Like</a><br>
  {% endif %}
  <strong">{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>




 <div class="container  p-5 border border-light">
    <div class="text-center font-weight-bold mb-3"><span>{{post.comment_numbers}}</span> comment{{post.comment_numbers | pluralize }}</div>
{% if comments %}
    {% for comment in comments %}
        <div class="media d-block d-md-flex  mb-3 border border-light container">
          <img class="card-img-64 d-flex mx-auto mb-3 mt-3"
            src="{{comment.name.profile.picture.url}}">
          <div class="media-body text-center text-md-left ml-md-3 ml-0 mb-4 mt-3">
            <p class="font-weight-bold my-0">
              {{comment.name}} | {{comment.date_added | date:'d F Y '}}
              <a href="" class="pull-right ml-1">
              </a>
              {% if user.is_authenticated and user == comment.name %}
          <a href="{% url 'core:dltz' comment.id %}" class="badge bg-danger float-right">Delete</a>
              {%endif%}
            </p>
            {{comment.comment | safe }}

            </div>
          </div>
    {% endfor %}

{% else %}
  <h4>No comments yet </h4>
{% endif %}

{% if user.is_authenticated %}
          <form method="POST" >
            {% csrf_token%}
            {{comment_form.comment}}
            <div class="text-center my-4">
              <button class="btn btn-info btn-sm" type="submit">Post</button>
            </div>
          </form>
{% else%}

<form method="POST" >
          {% csrf_token%}
      <textarea class="form-control" rows="4">  </textarea>
    <div class="text-center my-4">
    <a href="{% url 'login' %}?next={{request.path}}" class="btn btn-info btn-sm" type="submit">Post</a>
  </div>
</form>
{% endif %}



</div>
</div>
  <!-- Grid row -->


</div>


{% endblock content %}

templates/footer.html
<!--Footer-->
    <footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">

        <hr class="my-4">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-youtube mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-google-plus-g mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-dribbble mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-pinterest mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>

            <a href="" target="_blank">
                <i class="fab fa-codepen mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2021
            <a href="" target="_blank"></a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

templates/home.html
{% extends 'base.html' %}

   {% include 'partials/_navbar.html' %}

{% block title %}
  Blog
{% endblock %}

{% block content%}

 <section class="text">
    <hr class="my-5">
    <!-- Grid row -->
  <div class="row">
    {% for post in posts %}
    <!-- Grid column -->
    <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">

      <!-- Featured image -->
      <div class="view overlay rounded z-depth-2 mb-4">
        <img class="img-fluid" src="{{post.post_image.url}}"    alt="Sample image" style="height:300px;">
        <a href="{% url 'core:detail' post.slug %}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

      <!-- Category -->
      <a href="#!" class=" red-text">
        <h6 class="font-weight-bold mb-3"><i class="fas fa-map pr-2"></i>{{post.get_category_display}}</h6>
      </a>

      <!-- Post title -->

    <a href="{% url 'core:detail' post.slug %}">
      <h4 href= class="font-weight-bold mb-3"><strong>{{post.title}}</strong></h4>
    </a>

      <!-- Post data -->
      <p>by <a class="font-weight-bold">{{post.author}}</a>, {{post.date_created | date:"F d Y"}}</p>
      <!-- Excerpt -->
      <p class="dark-grey-text">{{post.content|truncatewords:50|safe}}</p>
      <!-- Read more button -->
      <a href="{% url 'core:detail' post.slug %}" class="btn btn-blue btn-rounded btn-md mb-5">Read more</a>

    </div>
</div>
    {%endfor%}

</div>

    <!--Grid row-->

    <!--Pagination-->
    {% if is_paginated%}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous%}
          <li class="page-item  ">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
            <li class="page-item ml-2">
            <a class="page-link" href="?page=1">{{page_obj.previous_page_number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}

            <li class="page-item   ml-2">
            <a class="page-link" href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>

          {% endif %}
        </ul>
      </nav>
      {% endif %}


</section>

{% endblock content %}

{% include 'partials/_footer.html '%}

</body>

</html>

templates/navbar.html
 <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="/" >
                    <strong class="blue-text">Blog</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link waves-effect" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                    </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link waves-effect font-weight-bold" href="{%url 'core:create'%}">Publish a Post </a>
                            </li>

                             <li class="nav-item dropdown">
                                <a class="nav-link waves-effect " href="{% url 'profile' user.username %}" >Profile</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link waves-effect " href="{% url 'edit-profile' user.username %}" >Edit Profile</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'settings' %}" >settings</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'logout' %}" >Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'login' %}">Login</a>
                            </li>

                             <li class="nav-item">
                                <a class="nav-link waves-effect" href="{% url 'register' %}" >Signup</a>
                            </li>
                        {% endif %}

                    </ul>

                </div>

            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->

templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}
{% block content %}
        <div class="content-section">
        <form method="POST"  enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{form.media}}
                {{ form | crispy }}
            </fieldset>
            <div class='form-group'>
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}